# Generated by Django 3.1.7 on 2021-09-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Insta', models.CharField(max_length=10)),
                ('Comments', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='MOOC',
        ),
    ]
